services:
  tofupilot:
    image: ghcr.io/tofupilot/tofupilot:latest
    depends_on:
      - edgedb
      - minio
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - tofupilot-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - tofupilot-network

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio ${STORAGE_INTERNAL_ENDPOINT_URL} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}; do
        echo 'Waiting for MinIO to be ready...'
        sleep 10
      done;
      mc mb myminio/${BUCKET_NAME} || true
      "
    networks:
      - tofupilot-network

  edgedb:
    image: edgedb/edgedb:latest
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      # Automatically apply migrations on startup
      EDGEDB_SERVER_MIGRATE_ON_START: "1"
    volumes:
      - "./dbschema:/dbschema:ro" # Read-only mount of the dbschema directory
      - "edgedb-data:/var/lib/edgedb/data"
    ports:
      - "${EDGEDB_PORT}:${EDGEDB_PORT}"
    networks:
      - tofupilot-network

networks:
  tofupilot-network:
    driver: bridge

volumes:
  edgedb-data:
  minio-data:
