services:
  tofupilot:
    image: ghcr.io/tofupilot/tofupilot:latest
    depends_on:
      edgedb:
        condition: service_healthy
      minio:
        condition: service_started
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - tofupilot-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - storage-data:/data
    command: server /data --console-address ":9001"
    networks:
      - tofupilot-network

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio ${STORAGE_INTERNAL_ENDPOINT_URL} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}; do
        echo 'Waiting for MinIO to be ready...'
        sleep 10
      done;
      mc mb myminio/${BUCKET_NAME} || true
      "
    networks:
      - tofupilot-network

  edgedb:
    image: edgedb/edgedb:latest
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "database-data:/var/lib/edgedb/data"
    ports:
      - "${EDGEDB_PORT}:${EDGEDB_PORT}"
    networks:
      - tofupilot-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${EDGEDB_PORT}/server/status/ready || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  tofupilot-network:
    driver: bridge

volumes:
  database-data:
  storage-data:
